x-constants:
  backend_host: &backend_host localhost
  backend_port: &backend_port 5000

services:
  frontend:
    image: smpolito/geocontrolui:latest
    restart: unless-stopped
    container_name: geocontrol-frontend
    ports:
      - "5173:5173" # Anchored variables defined above (e.g., &frontend_port) cannot be used within quoted strings.
        # Values like port numbers must be written explicitly as literals, but they should remain consistent with the defined variables.
    volumes: # Environment variables for the front-end must be defined in the frontend/env.vars.json and the file must be
      - ./frontend/env-vars.json:/app/dist/config.json # explicitly mounted in the container to be effective
    depends_on:
      - backend
  backend:
    container_name: geocontrol-backend
    restart: unless-stopped
    build:
      context: ../
      dockerfile: ./docker/backend/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend.sh:/backend.sh
      # - ..:/usr/src/app
    environment:
      APP_PORT: ${APP_PORT}
      DB_TYPE: ${DB_TYPE}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: root
      DB_PASSWORD: ${DB_PASSWORD}
    command: ["sh", "/backend.sh"]
    depends_on:
      - db
  db:
    image: mysql
    restart: unless-stopped
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql

volumes:
  db_data:
